- bigcommerce/resources/__init__.py
- bigcommerce/resources/webhooks.py
- tests/test_base.py
Add `Webhooks` module to support https://developer.bigcommerce.com/api/stores/v2/webhooks
> Add webhooks resource

- README.md
- bigcommerce/exception.py
- setup.py
Hey! I was looking into taking a shot at #15 when I noticed that there was a little bit of trailing whitespace in a couple places. This was all the occurrences I could find. :smile:
> Cleanup whitespace

- bigcommerce/resources/base.py
- bigcommerce/resources/products.py
- tests/test_base.py
I ended up not using this (and therefore not testing it thoroughly), but I think this takes care of the product counts unless I'm missing something.
Submitting for your consideration.
Regards!
> Support for product count operation

- CHANGELOG.md
- bigcommerce/resources/base.py
- bigcommerce/resources/brands.py
- bigcommerce/resources/categories.py
- bigcommerce/resources/coupons.py
- bigcommerce/resources/customer_groups.py
- bigcommerce/resources/customers.py
- bigcommerce/resources/option_sets.py
- bigcommerce/resources/options.py
- bigcommerce/resources/orders.py
- bigcommerce/resources/products.py
- bigcommerce/resources/redirects.py
- bigcommerce/resources/webhooks.py
- tests/test_base.py
* Allow override of paths in individual resources by creating a separate
method for it
* Extract delete_all into a CollectionDeleteable class and apply it
where it belongs (remove it from Webhooks)
* Add CHANGELOG file
> Refactor to allow override of paths

- CHANGELOG.md
- bigcommerce/resources/products.py
- tests/test_base.py
* This replaces https://github.com/bigcommerce/bigcommerce-api-python/pull/10
* Thanks @jtallieu !
> Add Google Shopping Mappings

- bigcommerce/resources/__init__.py
- bigcommerce/resources/currencies.py
> BIG-25887 - add currencies

- bigcommerce/resources/orders.py
Adding a new subresource for order messages. For the moment these are only listable and GETable (read-only).
> BIG-27792 - Add order message support

- bigcommerce/resources/__init__.py
- bigcommerce/resources/pages.py
Adding support for /pages/ resource
> API-395 add support for web content pages

- bigcommerce/resources/orders.py
> Add missing order taxes subresource

- CHANGELOG.md
- setup.py
Pulling in a few fixes from the community.
> Release 0.17.0

- bigcommerce/connection.py
- tests/test_connection.py
BC now supports GZIP, so let’s add support in this library!
> API-641 - support gzip

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Ticket: 
- [API-917](https://jira.bigcommerce.com/browse/API-917)
Added issue template, pr template, and contributing guidelines
> API-917: Add contributing guidelines and templates

- bigcommerce/connection.py
- tests/test_connection.py
Commit https://github.com/bigcommerce/bigcommerce-api-python/commit/a9d9ba016521d5c1b061c4c07bd6c28e55c3b333 refactored connection.py in such a way that the app installation process broke. This reverts those changes.
Fixes https://github.com/bigcommerce/bigcommerce-api-python/issues/66
> Revert to known good connection.py

- bigcommerce/connection.py
REF: http://docs.python-guide.org/en/latest/writing/gotchas/
> Do not use mutable objects as default arguments.

- bigcommerce/resources/__init__.py
- bigcommerce/resources/blog_posts.py
Add support for v2 /blog/posts endpoint
> Add Blog Posts resource

- bigcommerce/resources/pages.py
/v2/pages endpoint now supports count at /v2/pages/count.
Adding support for it in this library.
> Add count to pages

- bigcommerce/resources/products.py
Updated methods on ProductVideos class to include all allowable methods.
[Issue 77](https://github.com/bigcommerce/bigcommerce-api-python/issues/77)
> Updated allowable methods on ProductVideos

- requirements.txt
Update PyYAML dependency to latest version due to CVE.
> Update PyYAML to 5.1

- bigcommerce/api.py
- setup.py
Add a class method for `signed_payload_jwt` to BigcommerceApi
> Add class method for JWT payload and release 0.22.1

- bigcommerce/api.py
- bigcommerce/connection.py
- Refine JWT checking logic for better security & consistency
> Refine JWT checks

- requirements.txt
Updates pyjwt dependency to newest version.
- [APPEX-328](https://bigcommercecloud.atlassian.net/browse/APPEX-328)
Attach images or add image links here.
> APPEX-328 update pyjwt to 2.4.0
